### ISSUE TITLE
Client initialization needs to be moved ahead for delete_xpath operation

### ISSUE THREAD

**Issue by mahen-g** [cisco-ie/cisco-gnmi-python#82]
cisco-gnmi set 10.30.115.66:50051 -os NX-OS -root_certificates gnmi.pem -ssl_target_override ems.cisco.com -delete_xpath "/interfaces/interface[name='eth1/7']/subinterfaces/subinterface[index=0]/ipv4/addresses/address"
Username: admin
Password:
> /ws/mgangaia-sjc/pyats-latest/lib/python3.6/site-packages/cisco_gnmi/cli.py(292)gnmi_set()
-> if args.delete_xpath:
(Pdb) c
ERROR:root:Error during usage!
Traceback (most recent call last):
File "/ws/mgangaia-sjc/pyats-latest/lib/python3.6/site-packages/cisco_gnmi/cli.py", line 80, in main
rpc_map[args.rpc]()
File "/ws/mgangaia-sjc/pyats-latest/lib/python3.6/site-packages/cisco_gnmi/cli.py", line 292, in gnmi_set
if args.delete_xpath:
UnboundLocalError: local variable 'client' referenced before assignment

Thanks,
Mahendra

**Comment by mahen-g** [comment]
Also,  line 295, needs to be the below.  Insted of args.xpath, it should be args.delete_xpath

 delete_response = client.delete_xpaths(args.delete_xpath)
